### ISSUE TITLE
error in installing PBBAM lib for blasr

### ISSUE THREAD

**Issue by kumarsaurabh20** [PacificBiosciences/pbbam#3]
I tried to follow this guide (http://pbbam.readthedocs.org/en/latest/getting_started.html) to install pbbam library to make blasr compatible with bam files. I install all the dependent libraries and followed the guide. When I run 'make' I get the following error. Dont know if I am missing something:

 make[2]: *** [src/CMakeFiles/pbbam.dir/BarcodeQuery.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/pbbam.dir/all] Error 2
make: *** [all] Error 2
[pbbam_log.txt](https://github.com/PacificBiosciences/pbbam/files/158782/pbbam_log.txt)

**Comment by pezmaster31** [comment]
Hi,
From the log provided (thanks), it's trying to use Boost 1.53. You'll need 1.55+ . 

If you do have a newer version of Boost already on your system, you can indicate that explicitly to cmake:

     -DBoost_INCLUDE_DIRS="/path/to/boost" 

  - Derek

**Comment by kumarsaurabh20** [comment]
Hi Darek, Thanks for your reply. I have installed the latest version of boost -v 1.60.0 but when I attempt to install pbbam, in the log it still shows  boost version as 1.53. I have tried multiple times now..

**Comment by pezmaster31** [comment]
Did you try removing & re-creating the build directory, before re-running cmake with the Boost path? CMake can be a little finicky with how it caches/updates previous configuration data.

**Comment by kumarsaurabh20** [comment]
in the -DBoost_INCLUDE_DIRS="/path/to/boost", should I provide include directory path or the source folder?

I have not installed boost in default location. I have a build directory where all the source files are available and another folder with include and lib folder.

**Comment by pezmaster31** [comment]
The 'include' directory, pbbam only needs the headers.

**Comment by kumarsaurabh20** [comment]
Adding -DBoost_INCLUDE_DIRS with cmake did not work. Then I followed this link http://stackoverflow.com/questions/3808775/cmake-doesnt-find-boost  
and updated the CMakeLists.txt file withe following commands:

set(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} "C:/win32libs/boost")
set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} "C:/win32libs/boost/lib")

It passed the previous error but returned error in the end. Here is the log file:
[pbbam.txt](https://github.com/PacificBiosciences/pbbam/files/165688/pbbam.txt)

**Comment by pezmaster31** [comment]
Ah ok, by overriding the 'global' include path, boost/regex.h is now hiding /usr/include/regex.h...

Here's another approach:

  * comment out (or remove) the path changes you made to CMakeLists.txt
  * wipe & re-create the build directory
  * set the following environment variable:

    `$ export BOOST_ROOT="path/to/boost" ` 

  using the parent directory for include & lib (probably  "C:/win32libs/boost" from your previous comment).

  * and now run 

    `$ cmake .. [your other args]`
     `$ make`

Let me know how that goes.
  - D

**Comment by kumarsaurabh20** [comment]
So this time I freshly cloned the repository, defined the BOOST_ROOT and executed the build commands without modifying the CMakeLists.txt file. I think I have got the same results. Failed after 100% completion.
[pbbam2.txt](https://github.com/PacificBiosciences/pbbam/files/165809/pbbam2.txt)

**Comment by pezmaster31** [comment]
Hmm... ok, please run:

`$ make clean`
`$ make VERBOSE=1`

and attach that log. It's going to be a ton of output, but at least then I can see exactly what's being included/linked against.

**Comment by kumarsaurabh20** [comment]
as requested:
[pbbam3.txt](https://github.com/PacificBiosciences/pbbam/files/165881/pbbam3.txt)

**Comment by pezmaster31** [comment]
And just to double-check, since I didn't see your export command - you used the Boost root directory, not its include directory? 

In other words, this:
`$ export BOOST_ROOT="/home2/ISAD/ks575/software/dependent_libraries/build/boost_1_60_0"`
 
rather than this:
`$ export BOOST_ROOT="/home2/ISAD/ks575/software/dependent_libraries/build/boost_1_60_0/include"`

??

**Comment by kumarsaurabh20** [comment]
I used 
$ export BOOST_ROOT="/home2/ISAD/ks575/software/dependent_libraries/build/boost_1_60_0"

**Comment by pezmaster31** [comment]
Man, this one is weird. So we need to point CMake to your non-standard Boost location, no problem. But then it somehow hides the system \<regex.h\>... just weird. 

Anyway, turns out GTest actually has an internal regex engine that we can try to get it to use, rather than the POSIX one.

So add `-DGTEST_HAS_POSIX_RE=0` to this line :
https://github.com/PacificBiosciences/pbbam/blob/master/tests/CMakeLists.txt#L30

so it becomes:

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${PacBioBAM_CXX_FLAGS} -DGTEST_HAS_POSIX_RE=0 ")`

and run these guys as before, with your paths of course:

`$ export BOOST_ROOT=<path>`
`$ cmake .. [args]`
`$ make`

Preferably from a clean build directory.

**Comment by kumarsaurabh20** [comment]
Again the same error as pbbam3.txt. :(
I was wondering if my googletest library has a faulty installation?  It can be confirmed if the pbbam compilation checks in the beginning if the googletest is successfully compiled or not.

**Comment by pezmaster31** [comment]
Not exactly, as pbbam is pulling in GoogleTest source and building it internally - ensuring similar compiler version/flags for gtest & pbbam. But... my last suggestion wouldn't have actually affected the GTest compile flags - that change was in a different scope. My mistake. 

I still think this is the issue, from the errors listed, and forcing GTest to ignore <regex.h> is the way to go... so, insert this line:

`add_definitions("-DGTEST_HAS_POSIX_RE=0")`

in here: https://github.com/PacificBiosciences/pbbam/blob/master/CMakeLists.txt#L181

between the 'endif()' and 'add_subdirectory()' commands - so that GTest's compilation step actually gets passed the flag we need.

**Comment by kumarsaurabh20** [comment]
bingo... it worked. Many thanks for all your assistance in resolving this issue.

blasr has this configure file option --no-pbbam. 

`./configure.py --shared --sub --no-pbbam`

If I dont use this (--no-pbbam option) the software will be configured with pbbam library by default? Is this correct?

**Comment by pezmaster31** [comment]
Sweet, glad to hear it. 

I'll start a 'troubleshooting' section in the build portion of the docs, with this problem as an entry. And instead of requiring users to edit build files in the future, I'll add a cmake command-line option to enable this workaround. Thanks for being a patient guinea pig, not having your specific environment setup to test on over here. :)

As far as blasr's "--no-pbbam" option, I'm honestly not sure off the top of my head - whether that's just a setup flag (e.g. how it finds pbbam) or if it's a compile-time flag to enable/disable BAM support. I've seen code related to both, but am not familiar enough with blasr itself to know exactly how they are related. Feel free to post the question over on the blasr repo - where they can definitely give you a proper answer (and where other users might search for the same thing & find the response).

**Comment by pb-cdunn** [comment]
* https://github.com/PacificBiosciences/blasr/issues
